"""add feedback items

Revision ID: c7468a82a15d
Revises: cecadcc8d8ce
Create Date: 2026-10-04 01:22:51.767927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7468a82a15d'
down_revision: Union[str, None] = 'cecadcc8d8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presentation_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('timestamp_ref', sa.Float(), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_prompt_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_items_id'), 'feedback_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_items_id'), table_name='feedback_items')
    op.drop_table('feedback_items')
    # ### end Alembic commands ###
