"""add audio features

Revision ID: cecadcc8d8ce
Revises: ef120774102b
Create Date: 2026-10-04 01:10:55.680669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecadcc8d8ce'
down_revision: Union[str, None] = 'ef120774102b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presentation_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('window_seconds', sa.Float(), nullable=False),
    sa.Column('energy_rms', sa.Float(), nullable=True),
    sa.Column('is_silence', sa.Integer(), nullable=True),
    sa.Column('local_wpm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_features_id'), 'audio_features', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_features_id'), table_name='audio_features')
    op.drop_table('audio_features')
    # ### end Alembic commands ###
